"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AppPage from "@/components/AppPage";
import { DEMO_COMPANIES } from "@/lib/preloaded";
import { ALERTS_KEY, DEFAULT_ALERTS, AlertPreferences, getAlertPreferences } from "@/lib/workspace";

export default function AlertsPage(){
  const router=useRouter(); const [prefs,setPrefs]=useState<AlertPreferences>(DEFAULT_ALERTS); const [saved,setSaved]=useState(false);
  useEffect(()=>setPrefs(getAlertPreferences()),[]);
  const save=()=>{localStorage.setItem(ALERTS_KEY,JSON.stringify(prefs));setSaved(true);setTimeout(()=>setSaved(false),2000)};
  const triggered=DEMO_COMPANIES.filter(item=>prefs.enabled&&item.rdi>=prefs.threshold);
  return <AppPage><div className="mb-8"><p className="font-data-label text-primary uppercase text-[11px] tracking-widest mb-2">Monitoring</p><h1 className="text-5xl font-bold">Drift alerts</h1><p className="text-on-surface-variant mt-3">Configure local monitoring rules and inspect which tracked companies currently breach them.</p></div><div className="grid lg:grid-cols-12 gap-6"><section className="lg:col-span-7 space-y-3"><h2 className="font-data-label uppercase text-[11px] text-on-surface-variant mb-3">Triggered now · {triggered.length}</h2>{triggered.map(item=><button key={item.slug} onClick={()=>router.push(`/analyze/${item.slug}`)} className="w-full glass-panel rounded-xl p-5 text-left flex items-center justify-between"><div><strong className="text-xl">{item.name}</strong><p className="text-sm text-on-surface-variant mt-1">{item.driftType} · threshold {prefs.threshold}</p></div><span className="font-data-value text-4xl text-tertiary">{item.rdi}</span></button>)}{!triggered.length&&<div className="glass-panel rounded-xl p-10 text-center text-on-surface-variant">No tracked companies exceed the active threshold.</div>}</section><aside className="lg:col-span-5 glass-panel rounded-2xl p-6 h-fit"><div className="flex justify-between items-center mb-6"><h2 className="font-data-label uppercase text-primary">Alert rule</h2><button onClick={()=>setPrefs({...prefs,enabled:!prefs.enabled})} className={`px-3 py-1 rounded-full text-xs ${prefs.enabled?"bg-green-500/15 text-green-400":"bg-surface-container text-outline"}`}>{prefs.enabled?"Enabled":"Paused"}</button></div><label className="block mb-6"><span className="flex justify-between text-sm mb-2"><span>RDI threshold</span><strong>{prefs.threshold}</strong></span><input type="range" min="20" max="90" step="5" value={prefs.threshold} onChange={e=>setPrefs({...prefs,threshold:Number(e.target.value)})} className="w-full accent-primary"/></label><label className="block text-sm mb-4">Delivery<select value={prefs.channel} onChange={e=>setPrefs({...prefs,channel:e.target.value as AlertPreferences["channel"]})} className="intel-input rounded-lg px-3 py-2 w-full mt-2"><option value="email">Email summary</option><option value="slack">Slack webhook</option></select></label><label className="block text-sm mb-6">Frequency<select value={prefs.frequency} onChange={e=>setPrefs({...prefs,frequency:e.target.value as AlertPreferences["frequency"]})} className="intel-input rounded-lg px-3 py-2 w-full mt-2"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><button onClick={save} className="w-full bg-primary text-on-primary rounded-xl py-3 font-data-label text-[11px] uppercase">{saved?"Saved ✓":"Save alert rule"}</button><p className="text-[11px] text-outline mt-3">Preferences persist in this browser. External email and Slack delivery require a connected notification service.</p></aside></div></AppPage>
}
